name: build

on: push

jobs:
  linux-build:
    name: Linux Build Py${{ matrix.pyver }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: linux-build
        run: |
          python -m pip install -r requirements.txt
          pyinstaller --onefile app.py
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*
