name: build

on: push

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: window-build
        shell: bash
        run: |
          python -m pip install -r requirements.txt
          pyinstaller --onefile app.py
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*
